Add Javascript SDK project
seaplane-io/seaplane pull request #268
Opened 2022-11-07 13:49 UTC by tonilopezmr

2022-11-07 13:49 UTC, tonilopezmr commented
Current dependencies on/for this PR:
* main
  * **PR #268** <a href="https://app.graphite.dev/github/pr/seaplane-io/seaplane/268" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/seaplane-io/seaplane/268?utm_source=stack-comment).

2022-11-07 14:56 UTC, kbknapp reviewed
Looks like good scaffolding. I'd prefer to have at least some stubbing or functionality before merging to main. If you'd prefer you can always work against a feature branch incrementally and them merge that to main when ready?

At a minimum we should probably change the license of the tests module.

2022-11-07 14:56 UTC, kbknapp commented on seaplane-sdk/javascript/README.md
> +[LICENSE]: https://github.com/seaplane-io/seaplane/blob/main/LICENSE
We can remove all these unused links, no?

2022-11-07 14:56 UTC, kbknapp commented on seaplane-sdk/javascript/src/index.ts
> +}
I'm not usually a fan of committing hello-world stubs to a public repo, I'd prefer we flesh it out a little more before including or at a minimum just a an `error` saying it's under construction.

2022-11-07 14:56 UTC, kbknapp commented on seaplane-sdk/javascript/tests/index.js
> +console.log(result)
Same here

2022-11-07 15:31 UTC, tonilopezmr commented
I agree @kbknapp, I just wanted to upload everything in small steps to see progress, I'll continue working on this branch until I have the `Configuration` and `Seaplane` classes done.

Thanks for your review! 🎉

2022-11-07 16:03 UTC, kbknapp commented
No worries! Just ping me again when you're ready and I'll give the 👍🏻

2022-11-21 07:33 UTC, tiago-peres requested changes
Good with me... I'd just address all of @kbknapp's comments before merging

2022-11-23 09:04 UTC, tiago-peres approved these changes
LGTM

2022-11-23 14:28 UTC, merged

2022-11-23 14:40 UTC, tonilopezmr commented
This Linear [CUST-264](https://linear.app/seaplane/issue/CUST-264/metadata-api) was included here as well